config/routes.rb
Rails.application.routes.draw do
  #devise_for :users

  #need to extend devise ctrl to deal with the phone, address etc fields
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :products
  resources :categories
  resources :recipes
  resources :oitems
  resources :carts
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  
match '/categories/:category_id/get_products' => 'categories#get_products', :via => [:get], :as => 'get_products'

match '/recipes/save_direction' => 'recipes#save_direction', :via => [:post], :as => 'save_direction'

match '/recipes/remove_direction' => 'recipes#remove_direction', :via => [:post], :as => 'remove_direction'

match '/recipes/edit_direction' => 'recipes#edit_direction', :via => [:post], :as => 'edit_direction'

match '/recipes/save_anyingredient' => 'recipes#save_anyingredient', :via => [:post], :as => 'save_anyingredient'

match '/recipes/remove_anyingredient' => 'recipes#remove_anyingredient', :via => [:post], :as => 'remove_anyingredient'

match '/recipes/edit_anyingredient' => 'recipes#edit_anyingredient', :via => [:post], :as => 'edit_anyingredient'

match '/carts/associate_user_with_cart' => 'carts#associate_user_with_cart', :via => [:post], :as => 'associate_user_with_cart'

match '/products/filter_products' => 'products#filter_products', :via => [:post], :as => 'filter_products'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients,inverse_of: :recipe, dependent: :destroy
  has_many :directions,inverse_of: :recipe, dependent: :destroy
  has_many :anyingredients,inverse_of: :recipe, dependent: :destroy
  has_many :products, through: :ingredients
  has_one_attached :recipeimg
 

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

  accepts_nested_attributes_for :anyingredients, reject_if: :all_blank, allow_destroy: true

  validates :title, :description, presence: true

  validate :image_ok

  private
  def image_ok
    if recipeimg.attached? && !recipeimg.content_type.in?(%w(image/jpeg image/png image/jpg))
      errors.add(:recipeimg, 'must be png or jpg')
    end
  end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy, :save_direction, :remove_direction, :save_anyingredient, :remove_anyingredient, :edit_direction, :edit_anyingredients]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    
    @recipe = Recipe.new
    @recipe.products.build
    @recipe = Recipe.new
    5.times { @recipe.directions.build }
    5.times { @recipe.anyingredients.build }
    #@recipe.anyingredients.build
  end

  def create
    @isNewPath = true
    @recipe = Recipe.new(recipe_params)

    # if(@recipe.save)
    #   #commenting this to check if the stepped form from w3 will work
    #   redirect_to @recipe, notice: "Recipe created"
    # else
    #   render 'new'
    # end

    respond_to do |format|
      if @recipe.save
        #save after title, desc, image and product associations
        #now to add the directions and ingredients
        format.html { redirect_to edit_recipe_path(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
        format.js
      end
    end
      
  end

  def edit
    @recipe.products.build

  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "Recipe updated"
    else
      render 'edit'
    end

  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path

  end

  def save_direction
    direction = @recipe.directions.build(:step => params[:step])

     if @recipe.save
      #refresh page
      redirect_to edit_recipe_path(@recipe.id)
     else
       puts "#{params[:step]}"
    end
  end

  def remove_direction
   
    direction = Direction.find(params[:direction_id])
    @recipe.directions.delete(direction)

    #refresh TODO Needs js
    redirect_to edit_recipe_path(@recipe.id)


    # The collection.delete method removes one or more objects from the collection by setting their foreign keys to NULL

    # eg @author.books.delete(@book1)

    # Additionally, objects will be destroyed if they're associated with dependent: :destroy, and deleted if they're associated with dependent: :delete_all.

  end

  def edit_direction
    direction = Direction.find(params[:direction_id])
    direction.update(:step => params[:step])
    redirect_to edit_recipe_path(@recipe.id)
  end

  def save_anyingredient
    anyingredient = @recipe.anyingredients.build(:name => params[:name])

     if @recipe.save
      #refresh page
      redirect_to edit_recipe_path(@recipe.id)
     else
       puts "#{params[:name]}"
    end
  end

  def remove_anyingredient
   
    anyingredient = Anyingredient.find(params[:anyingredient_id])
    @recipe.anyingredients.delete(anyingredient)
    redirect_to edit_recipe_path(@recipe.id)

  end

  def edit_anyingredient
    anyingredient = Anyingredient.find(params[:anyingredient_id])
    anyingredient.update(:name => params[:name])
  end




  private 

  def recipe_params
    params.require(:recipe).permit(:title, :description, :recipeimg, 
      ingredients_attributes: [:id, :name, :_destroy],
        directions_attributes: [:id, :step, :_destroy],
        product_ids: [],
        anyingredients_attributes: [:id, :name, :_destroy])
  end

 
  def find_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/views/recipes/_anyingredient_fields.html.erb
<div class='nested-fields'>
    <%= f.input :name, input_html: {class: "form-input form-control"} %>
 
    <%= link_to_remove_association "remove ingredient", f, class: "form-button btn btn-default" %>
</div>

app/views/recipes/_direction_fields.html.erb
<div class='nested-fields'>
    <%= f.input :step %>
    <%= link_to_remove_association "remove step", f, class: 'btn btn-danger btn-xs' %>
</div>

app/views/recipes/_edit_recipe.html.erb
    <div class="row" id="ingredients">
      <h3>Ingredients</h3>
        <%= render 'anyingredients/add_any_ingredient' %>
        <table class="table table-hover">
          <thead>
          <tr>
            <td class="col-md-3"><strong>Ingredient</strong></td>
            <td class="col-md-3"></td>
            <td class="col-md-3"></td>
            <td class="col-md-3"></td>
          </tr>
          </thead>
            <tbody>
              <% @recipe.anyingredients.each do |anyingredient| %>
              <tr>
                <td class="col-md-3"><%=anyingredient.name %></td>
                <td class="col-md-3">
                    <div id="ing-<%=anyingredient.id %>" class="collapse">
                       <%= render 'anyingredients/edit_anyingredient',anyingredient:anyingredient %>
                    </div>
                  </td>
                  <td class="col-md-3">
                     <a class="btn btn-info btn-xs" 
                    role="button" data-toggle="collapse" href="#ing-<%=anyingredient.id %>" 
                    aria-expanded="false" aria-controls="collapseAnyIngredient"> Edit
                    </a>
                  </td>
                   <td class="col-md-3">
                  <%= render 'anyingredients/remove_anyingredient',anyingredient:anyingredient %>
                </td>
              </tr>
              <% end %>
          </tbody>
        </table>
    </div>

      <div class="row" id="directions">
        <h3>Directions</h3>
        <%= render 'directions/add_new_step' %>
        <table class="table table-hover">
          <thead>
            <tr>
              <td class="col-md-3"><strong>Step#</strong></td>
              <td class="col-md-3"></td>
              <td class="col-md-3"></td>
              <td class="col-md-3"></td>
            </tr>
          </thead>
          <tbody>
            <% @recipe.directions.each do |direction| %>
               <tr>
                <td class="col-md-3"><%= direction.step %> </td>
                <td class="col-md-3">
                  <div id="direction-<%=direction.id %>" class="collapse">
                       <%= render 'directions/edit_step',direction:direction %>
                  </div>
                </td>
                <td  class="col-md-3"><a class="btn btn-info btn-xs" 
                    role="button" 
                    data-toggle="collapse" 
                    href="#direction-<%=direction.id %>" 
                    aria-expanded="false" 
                    aria-controls="collapseAddDirection">Edit
                    </a>
                </td>
                <td class="col-md-3"><%= render 'directions/remove_step',direction:direction %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
        

              
                
              

            
      
             
                
           
       
      </div>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>

    <% if @recipe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

        <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, class:'form-label' %>
      <%= f.text_field :title, class:'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description, class:'form-label' %>
      <%= f.text_area :description, class:'form-control' %>
    </div>

  <h5>Choose Products to Associate with this recipe</h5>
   <div class="field">
      <p>
      <%= hidden_field_tag "recipe[product_ids][]", nil %>
        <% Product.all.each do |cat| %>
          <%= check_box_tag "recipe[product_ids][]",  cat.id, @recipe.product_ids.include?(cat.id), id: dom_id(cat) %>
          <%= label_tag dom_id(cat), cat.title %>
          <%= link_to  "edit product", edit_product_path(cat.id) %><br>
        <% end %>
      </p>
    </div>

    <h3>Image</h3>
    <p>
      <%= f.label :recipeimg, class:'form-label' %>
      <%= f.file_field(:recipeimg) %>
    </p>

    <% if @isNewPath %>
      <% render 'new_recipe', f:f %>
    <% end %>


    
  <%= f.submit 'Save Recipe', :class => 'btn btn-danger' %>
<% end %>






   

    


 

app/views/recipes/_new_recipe.html.erb
    <h3>Directions</h3>
    <% @recipe.directions.each do |d| %>
    <p><%= d.step %></p>
    <% end %>
    <p>
    <%= f.fields_for :directions, Direction.new do |ff| %>
      <%= ff.label :step %>
      <%= ff.text_area :step, class:'form-control' %>
      <%= ff.submit 'add another direction', :class => 'btn btn-success btn-xs' %>
    <% end %>
    </p>

    <h3>Ingredients</h3>
    <% @recipe.anyingredients.each do |d| %>
    <p><%= d.name %></p>
    <% end %>
    <p>
    <%= f.fields_for :anyingredients, Anyingredient.new do |ff| %>
      <%= ff.label :name %>
      <%= ff.text_area :name, class:'form-control' %>
      <%= ff.submit 'anoother', :class => 'btn btn-success btn-xs' %>
    <% end %>
    </p>

app/views/recipes/edit.html.erb
<h1>Edit recipe</h1>
<%= render 'form' %>
<%= render 'edit_recipe' %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<div class="row">
<% @recipes.each do |r| %>
    <div class="col-md3">
    <% if r.recipeimg.attached? %>
    <p><%= image_tag r.recipeimg, class: "img-thumbnail" %></p>
    <% end %>
    <h3><%= link_to r.title, r %></h3>
    <p><%= r.description %></p>
    </div>
<% end %>

</div>



<%=link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>new recipe</h1>
<%= render 'form', recipe: @recipe %>
<br>
<%= link_to 'Back', root_path %>

app/views/recipes/show.html.erb
<div class="row">
   
    <h1>
    <%= @recipe.title %></h1>

    <% if @recipe.recipeimg.attached? %>
    <p><%= image_tag @recipe.recipeimg %></p>
    <% end %>
    
    <small>
        <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
        <%= link_to 'Back', recipes_path %> |
        <%= link_to 'Delete', recipe_path,  method: :delete, data: {confirm: "are you sure?"} %>
    </small>
    </h2>
    <h3>Description:</h3>
    <p><%= @recipe.description %></p>


    <h3>Ingredients/Products</h3>
    <ul>
        <% @recipe.products.each do |p| %>
        <li>
        <strong><%= link_to p.title, product_path(p) %></strong>
        <small> Only<%= link_to p.price, product_path(p) %> per kg</small>
        </li>
        <% end %>

        <% @recipe.anyingredients.each do |p| %>
        <li><%= p.name %></li>
        <% end %><br>
    </ul>

    <h3>Directions</h3>
    <ol>
    <% @recipe.directions.each do |p| %>
    <li><%= p.step %></li>
    <% end %><br>
    </ol>

   
</div>





