config/routes.rb
Rails.application.routes.draw do
  #devise_for :users

  #need to extend devise ctrl to deal with the phone, address etc fields
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :products
  resources :categories
  resources :recipes
  resources :oitems
  resources :carts
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  
match '/categories/:category_id/get_products' => 'categories#get_products', :via => [:get], :as => 'get_products'

match '/recipes/save_direction' => 'recipes#save_direction', :via => [:post], :as => 'save_direction'

match '/recipes/remove_direction' => 'recipes#remove_direction', :via => [:post], :as => 'remove_direction'

match '/recipes/edit_direction' => 'recipes#edit_direction', :via => [:post], :as => 'edit_direction'

match '/recipes/save_anyingredient' => 'recipes#save_anyingredient', :via => [:post], :as => 'save_anyingredient'

match '/recipes/remove_anyingredient' => 'recipes#remove_anyingredient', :via => [:post], :as => 'remove_anyingredient'

match '/recipes/edit_anyingredient' => 'recipes#edit_anyingredient', :via => [:post], :as => 'edit_anyingredient'

match '/carts/associate_user_with_cart' => 'carts#associate_user_with_cart', :via => [:post], :as => 'associate_user_with_cart'

match '/products/filter_products' => 'products#filter_products', :via => [:post], :as => 'filter_products'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :prodcats, inverse_of: :category
  has_many :products, through: :prodcats

  validates :title, presence: true

  accepts_nested_attributes_for :prodcats, allow_destroy: true

  accepts_nested_attributes_for :products, allow_destroy: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :prodcats,inverse_of: :product, dependent: :destroy
  has_many :ingredients,inverse_of: :product, dependent: :destroy
  has_many :categories, through: :prodcats
  has_many :recipes, through: :ingredients
  has_many :oitems, dependent: :delete_all
  has_one_attached :productimg
  belongs_to :user, :optional => true

  validates :title, presence: true
  

  accepts_nested_attributes_for :categories, allow_destroy: true
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  accepts_nested_attributes_for :prodcats, allow_destroy: true

  validates :title, :description, :price, presence: true

  WEIGHT = ["100", "250", "500", "1000"]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def get_products
    @category = Category.find(params[:category_id])

    #products with this category id
    products = @category.products
    @products = @category.products
    #init array, will need to add product details from product table as well as product img url from the active storage attachments table
    to_send = []
   
      products.each do |product|
        if product.productimg.attached?

        #get the img url
        img_url = 
        Rails.application.routes.url_helpers.rails_blob_path(product.productimg, only_path: true)

        #add product and img dets to array
        to_send.push(:product => product, :img_url => img_url)
      end

    end
    #puts "\n\n\n to send: #{to_send}"
 #redirect_to get_products

  respond_to do |format|
    #respons to js request for homepage
   format.json { render :json => to_send }
  
    #so regular page works too
    
  end
   end


  def index
    @categories = Category.all
  end

  def new

    
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    #render plain: params[:category].inspect
    @category = Category.new(category_params)
    if(@category.save)
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if(@category.update(category_params))
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:title,
      products_attributes: [:id, :title, :_destroy, :productimg],
      prodcats_attributes: [:category_id, :product_id, :_destroy],
      product_ids: [] )
  end

  
end

app/views/categories/_sidebar.html.erb

<div class="col col-md-3 col-sm-3 col-lg-3" id="getcontent" >
  <p>
    <%= form_tag(products_path, method: :get)do %>
      <% for category in @all_categories %>
        <div class="form-group">
          <%= check_box_tag "category_ids[]", category.id, @cat_ids.include?(category.id.to_s) %>
        </div>
        <div class="form-group">
        <%= "#{category.title} (#{category.products.count})" %><br>
        </div>
      <% end %>
      <%= submit_tag "Go", class:"btn btn-warning btn-sm" %>
    <% end %>
  </p>
</div><%# end categories sidebar %>

app/views/categories/edit.html.erb
<h1>edit category</h1>

<%= form_for :category, url: category_path(@category), method: :patch do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

<h4>Products</h4>
  <div class="field">
    <p>
   <%= hidden_field_tag "category[product_ids][]", nil %>
    <% @category.products.each do |p| %>
      <%= check_box_tag "category[product_ids][]",  p.id, @category.product_ids.include?(p.id), id: dom_id(p) %>
      <%= label_tag dom_id(p), p.title %>
      <%= link_to  "edit product", edit_product_path(p.id) %><br>
    <% end %>
  </p>
  </div>






  <p><%= f.submit({:class => 'btn'})%>
<% end %>

<h3>Products in <% @category %> category </h3>

<% @category.products.each do |p| %>
 <p> <strong><%= link_to p.title, product_path(p) %></strong></p>
<% end %><br>


app/views/categories/index.html.erb
<h1>Categories</h1>
 <% @categories.each do |category| %>

    <p><%= category.title %>
    
      <%= link_to 'show', category_path(category) %>
      <%= link_to 'edit', edit_category_path(category) %>
      <%= link_to 'delete', category_path(category), 
method: :delete,
data: {confirm: 'sure?'} %>
  </p>

 <% end %>
    <p><%=link_to 'New Category', new_category_path %></p>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_for :category, url: categories_path do |f| %>


  <p>
    <%= f.label :title %>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>


  <p><%= f.submit({:class => 'btn'})%>
<% end %>

app/views/categories/show.html.erb
<h3>Category</h3>


<h2><%= @category.title %></h2>
<%= link_to 'edit', edit_category_path(@category) %>

<%= link_to 'delete', category_path(@category), 
method: :delete,
data: {confirm: 'sure?'} %>