config/routes.rb
Rails.application.routes.draw do
  #devise_for :users

  #need to extend devise ctrl to deal with the phone, address etc fields
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :products
  resources :categories
  resources :recipes
  resources :oitems
  resources :carts
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  
match '/categories/:category_id/get_products' => 'categories#get_products', :via => [:get], :as => 'get_products'

match '/recipes/save_direction' => 'recipes#save_direction', :via => [:post], :as => 'save_direction'

match '/recipes/remove_direction' => 'recipes#remove_direction', :via => [:post], :as => 'remove_direction'

match '/recipes/edit_direction' => 'recipes#edit_direction', :via => [:post], :as => 'edit_direction'

match '/recipes/save_anyingredient' => 'recipes#save_anyingredient', :via => [:post], :as => 'save_anyingredient'

match '/recipes/remove_anyingredient' => 'recipes#remove_anyingredient', :via => [:post], :as => 'remove_anyingredient'

match '/recipes/edit_anyingredient' => 'recipes#edit_anyingredient', :via => [:post], :as => 'edit_anyingredient'

match '/carts/associate_user_with_cart' => 'carts#associate_user_with_cart', :via => [:post], :as => 'associate_user_with_cart'

match '/products/filter_products' => 'products#filter_products', :via => [:post], :as => 'filter_products'

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :prodcats,inverse_of: :product, dependent: :destroy
  has_many :ingredients,inverse_of: :product, dependent: :destroy
  has_many :categories, through: :prodcats
  has_many :recipes, through: :ingredients
  has_many :oitems, dependent: :delete_all
  has_one_attached :productimg
  belongs_to :user, :optional => true

  validates :title, presence: true
  

  accepts_nested_attributes_for :categories, allow_destroy: true
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  accepts_nested_attributes_for :prodcats, allow_destroy: true

  validates :title, :description, :price, presence: true

  WEIGHT = ["100", "250", "500", "1000"]
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index,:show, :filter_products]
  # GET /products
  # GET /products.json
  def index
  
   @home_page = true

    if params[:category_ids]
      #filter
      @cat_ids = params[:category_ids]
      @products = Product.joins(:categories).where('categories.id IN (?)', params[:category_ids])
    else
      #all
      @cat_ids = []
      @products = Product.all

    end
    @cart =  current_cart
    
  end

  def filter_products
    puts "filter params: #{params}"
    #get products in this cat
    @cat_ids = params[:category_ids] || []
    @products = Product.joins(:categories)
    .where('categories.id IN (?)', params[:category_ids])

   # category = Category.find(params[:category_id])
   # @products = category.products
    
    #re render view to update 
    #redirect_to :action => :index,:filter_products => true
    render :index

  end

  # GET /products/1
  # GET /products/1.json
 
  def show
    
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.categories.build
  end

  # GET /products/1/edit
  def edit
    puts params
    puts "/n/n/n/n here:#{params[:categories_attributes]}"
    @product.categories.build
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    puts "/n/n/n/n oh:#{params[:product][:categories_attributes]}"
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price,:productimg,
        categories_attributes: [:id, :title, :_destroy],
    category_ids: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_to_cart.html.erb
<p>
        <%= form_tag oitems_path do %>
          <%= hidden_field_tag :product_id, product.id %>
        <div class="form-group">Weight
          <%= select_tag(:weight, options_for_select(Product::WEIGHT, selected: :weight )) %>
        </div>
        <%= submit_tag 'add to cart' , class: "btn btn-warning btn-sm" %>
        <% end %>
      </p> 

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class:'form-control' %>
  </div>

   <h3>Image</h3>
        <p>
      	  <%= form.label :productimg %>
          <%= form.file_field(:productimg, {:class => 'form-control'}) %>
    </p>

  <h4>Categories</h4>
  <div class="field">
    <p>
   <%= hidden_field_tag "product[category_ids][]", nil %>
    <% Category.all.each do |cat| %>
      <%= check_box_tag "product[category_ids][]",  cat.id, @product.category_ids.include?(cat.id), id: dom_id(cat) %>
      <%= label_tag dom_id(cat), cat.title %>
      <%= link_to  "edit category", edit_category_path(cat.id) %><br>
    <% end %>
  </p>
  </div>

  <%
=begin%>
 <h4>Add New Category</h4>
  <%= form.fields_for :categories do |p| %>
    <p>
      <%= p.label :title %>
      <%= p.text_field :title, class:'form-control' %>
    </p>
  <% end %> 
<%
=end%>

 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="col col-md-9 col-sm-9 col-lg-9 theProducts">
  <% @products.each do |product| %>
    <div class="col col-md-4 col-sm-4 col-lg-4">
      <h3><%= product.title %></h3>
      <% if product.productimg.attached? %>
            <!-- product.image.present? will always return true, use attached? to check presence -->
        <p><%= image_tag product.productimg, class: "img-thumbnail" %></p>
      <% end %>

      <p><%= product.description.truncate(250) %></p>
      <p><strong><%= number_to_currency(product.price , unit: "€")%></strong> per gram</p>
      
      <p><%= link_to 'Read More', product %></p>

      <% if current_user && current_user.admin %>
        <p>
          <span><%= link_to 'Edit', edit_product_path(product) %></span> | 
          <span><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></span> | 
          <span><%= link_to 'New Product', new_product_path %></span>
        </p>
      <% end %>
  
      <%= render 'add_to_cart', product:product %>  
    </div> 
  <% end %>
</div>sssssss

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h2>
  <%= @product.title %>
  <small>
    <% if current_user && current_user.admin %>
    <%= link_to 'Edit', edit_product_path(@product) %> |
    <% end %>
    <%= link_to 'Back', root_path %>
  </small>
</h2>
<% if @product.productimg.attached? %>
    <!-- product.image.present? will always return true, use attached? to check presence -->
    <p><%= image_tag @product.productimg, class: "img-thumbnail" %></p>
<% end %>


<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%=number_to_currency(@product.price , unit: "€") %>

</p>
 <%= render 'add_to_cart', product:@product %>  

<% if @product.recipes.count > 0 %>
<h3>Recipes featuring <%= @product.title %></h3>
      <% @product.recipes.each do |r| %>
        <li>
        <strong><%= link_to r.title, recipe_path(r) %></strong>
        
        </li>
        <% end %>
<% end %>

<h3>Categories</h3>

<% @product.categories.each do |cat| %>
  <strong><%= link_to cat.title, category_path(cat) %></strong><small> link should to to all products in this cat?</small>
<% end %><br>